### ISSUE TITLE
Problem running the Docker container: exists(physicsFilename)

### ISSUE THREAD

**Issue by shakenes** [saimwani/multion-challenge#1]
Hi, 
I am trying to run the docker container as described in the Readme using `docker run -v ${MULTION_DATA_PATH}/data:/multion-chal-starter/data --runtime=nvidia multi_on:latest` but I'm getting the following error:

```
2021-03-04 10:01:30,682 Initializing dataset MultiNav-v1
2021-03-04 10:01:30,684 initializing sim Sim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0304 10:01:30.739068    16 ResourceManager.cpp:340] Check failed: Cr::Utility::Directory::exists(physicsFilename)
*** Check failure stack trace: ***
submit.sh: line 2:    16 Aborted                 (core dumped) python evaluate.py
```

Could it be a problem with the Matterport dataset? I downloaded it using `python download_mp.py --task habitat -o path/to/download/`. I hope this is correct!?

**Comment by saimwani** [comment]
Hi, 
You probably don't have the MultiON target objects inside the data folder. We have updated this repository to include the target objects within the `data` directory. Please try to follow the (updated) instructions once again and let us know if you face an issue.

**Comment by shakenes** [comment]
Thanks! It works now.
