### ISSUE TITLE
Is the standard test phase conducted on the 'Minival' split?

### ISSUE THREAD

**Issue by 82magnolia** [saimwani/multion-challenge#3]
Hello,

After looking through evaluate.py and habitat/core/benchmark.py, I realized that the --phase flag in evaluate.py does not have any effect. Is this true? It seems like the episodes generated are solely dependent on the DATA_PATH field of configs/tasks/multinav_mp3d.yaml. If this is the case, what is the difference between standard test phase and minival phase?

**Comment by saimwani** [comment]
Hi,

Yes, the `--phase` flag is not used, and it is not passed in the `submit.sh` provided. The Test Standard Phase uses a separate set of 1000 episodes which are not the same as the Minival split with 25 episodes. `multinav_mp3d.yaml` file is replaced before evaluation.

**Comment by 82magnolia** [comment]
I see. Thanks!
